export const layoutData: any = {
  global: {
    borderEnableAutoHide: true,
    borderMinSize: 100,
    splitterExtra: 7,
    splitterSize: 3,
    tabEnablePopout: false,
    tabSetEnableClose: false,
    tabSetEnableTabWrap: true,
    tabSetMinHeight: 100,
    tabSetMinWidth: 100,
    tabSetEnableMaximize: false,
  },
  borders: [
    {
      type: "border",
      location: "left",
      children: [
        {
          borderWidth: 265,
          component: "main_logo",
          enableClose: false,
          id: "#bab9r89a-owf7-42jf-5dq3-yah8kfe2891n",
          name: "Files",
          type: "tab",
        },
        {
          borderWidth: 265,
          component: "files",
          enableClose: false,
          id: "#0a7988f1-0cfb-4420-a2a3-8aa8af12684f",
          name: "Files",
          type: "tab",
        },
        {
          borderWidth: 265,
          component: "projects",
          enableClose: false,
          id: "#ab2da468-e13f-4925-b15a-388c00186737",
          name: "Projects",
          type: "tab",
        },
        {
          borderWidth: 265,
          component: "reports",
          enableClose: false,
          id: "#ab2da468-f54f-4831-gj5b-35ncl0196737",
          name: "Reports",
          type: "tab",
        },
        {
          borderWidth: 265,
          component: "workspaces",
          enableClose: false,
          id: "#ab57e4b8-e3gf-5h25-1bsa-3bbck01865n7",
          name: "Workspaces",
          type: "tab",
        },
        {
          borderWidth: 265,
          component: "users",
          enableClose: false,
          id: "#ac3dd4e8-wsf6-4tu0-mz3a-lo0c0018f7k7",
          name: "Users",
          type: "tab",
        },
        {
          borderWidth: 265,
          component: "workflows",
          enableClose: false,
          id: "#bb5db468-b1mg-u821-bxva-p80ch018j7i7",
          name: "Workflows",
          type: "tab",
        },
        {
          borderWidth: 265,
          component: "jobs",
          enableClose: false,
          id: "#aabd34c8-ll7y-4j2f-bdqa-3d8s001k67l7",
          name: "Jobs",
          type: "tab",
        },
        {
          borderWidth: 265,
          component: "ai_assistant_border",
          enableClose: false,
          id: "#babc31c8-ll7y-g7pf-mdpa-3d8s901kl7p7",
          name: "AI Assistant",
          type: "tab",
        },
        {
          borderWidth: 265,
          component: "search_border",
          enableClose: false,
          id: "#0a7988f1-9v73-f4d3-5twr-1zab6f1l6k48",
          name: "Search",
          type: "tab",
        },
        {
          borderWidth: 265,
          component: "my_workspaces_border",
          enableClose: false,
          id: "#bvn35lhs-t4dy-jk0p-mm6u-ml3kpy16lw0q",
          name: "My Workspaces",
          type: "tab",
        },
        {
          borderWidth: 265,
          component: "profile_border",
          enableClose: false,
          id: "#ba1cn1c8-9k7y-0epq-mdpa-md3sp014lhpg",
          name: "User Profile",
          type: "tab",
        },
      ],
    },
  ],
  layout: {
    id: "#baeaf63a-7e31-4f5b-836c-6aec43cb228a",
    type: "row",
    children: [
      {
        id: "#8b1bc920-89fb-4fe7-bad3-9cf70d693118",
        type: "tabset",
        weight: 75,
        children: [],
      },
    ],
  },
  popouts: {},
};
