FROM node:latest

WORKDIR /app

ENV NODE_OPTIONS="--max-old-space-size=4096"

COPY ./package.json .

# COPY ./package-lock.json .

RUN npm install --force

COPY . .

EXPOSE 5173

CMD ["npm", "run", "start-watch"]